 fill_blanks: [
                        { q: "A ___ looks like a typewriter.", a: "keyboard", options: ["keyboard", "monitor", "printer", "mouse"] },
                        { q: "The devices which are used to give commands are known as ___ devices.", a: "input", options: ["input", "output", "storage", "processing"] },
                        { q: "The ____ is also called as Visual Display unit.", a: "Monitor", options: ["Monitor", "CPU", "Keyboard", "UPS"] },
                        { q: "The ___ is used to play games and make a drawing as well.", a: "mouse", options: ["mouse", "printer", "CPU", "scanner"] },
                        { q: "The devices which are used to give results are called ___ devices.", a: "output", options: ["output", "input", "storage", "display"] },
                        { q: "A ___ uses computers to make test papers and exam reports.", a: "teacher", options: ["teacher", "doctor", "pilot", "banker"] },
                        { q: "A ___ looks like a television screen.", a: "monitor", options: ["monitor", "keyboard", "printer", "mouse"] },
                        { q: "Computers help doctors to perform ___.", a: "operations", options: ["operations", "lessons", "cooking", "billing"] },
                        { q: "Computers are used to withdraw money from ___.", a: "ATMs", options: ["ATMs", "schools", "hospitals", "libraries"] },
                        { q: "In banks, computers are used to maintain ___ of customers.", a: "accounts", options: ["accounts", "timetables", "report cards", "recipes"] },
                        { q: "In shopping malls, computers are used to generate ___.", a: "bills", options: ["bills", "exams", "medicines", "drawings"] },
                        { q: "Computers help in booking ___ at railway stations and airports.", a: "tickets", options: ["tickets", "rooms", "meals", "books"] },
                        { q: "Computers are used to prepare ___ for schools.", a: "timetables", options: ["timetables", "bills", "bank statements", "flight charts"] },
                        { q: "Students can draw and ___ with the help of a computer.", a: "colour", options: ["colour", "dance", "swim", "sleep"] },
                        { q: "You can solve ___ on a computer.", a: "sums", options: ["sums", "stories", "drawings", "songs"] },
                        { q: "AI helps doctors in _____.", a: "hospitals", options: ["hospitals", "malls", "banks", "schools"] },
                        { q: "AI robots can ____ your house ", a: "clean", options: ["clean", "paint", "build", "cook"] },
                        { q: "AI helps at ____ to make lesson fun.", a: "schools", options: ["schools", "hospitals", "airports", "malls"] }
                    ],